apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{.Values.redis.port}}
      targetPort: {{.Values.redis.port}}
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP